# NumPy

## Resources
1. Intro to numerical computing with NumPy (Beginner) | Alex Chobot-Leclerc (https://www.youtube.com/watch?v=V0D2mhVt7NE)

# Important things to know
1. numpy array is **row-important** (don't use np matrix, MATALB is column-important)
2. numpy array is different from python array

In [2]:
a = [1, 2, 4, 5]
b = [4, 6, 9, 20]
a+b

[1, 2, 4, 5, 4, 6, 9, 20]

### Array creation

In [3]:
import numpy as np
a = np.array([1, 2, 4, 5])
b = np.array([4, 6, 9, 20])
a+b

array([ 5,  8, 13, 25])

In [26]:
a.ndim

1

In [7]:
a.shape

(4,)

In [14]:
a.dtype

dtype('int32')

In [16]:
c = np.array([[8, 9, 10], [11, 20, 22]])

In [17]:
c

array([[ 8,  9, 10],
       [11, 20, 22]])

### Slicing -- var[lower:upper:step]

In [21]:
c[0,0]

8

In [22]:
#Partial indexing
c[0]

array([ 8,  9, 10])

It is important to remember that lower-bound element is included, but the upper-bound element is **not** included.

In [24]:
a = np.array([10, 11, 12, 13, 14])
a[1:3]

array([11, 12])

Omitted boundaries are assumed to be the beginning (or end) of the list

In [25]:
a[:3]

array([10, 11, 12])

![](numpy/1.png)